scan_filter_chain:
- name: box
  type: laser_filters/LaserScanBoxFilter
  params:
    invert: false
    box_frame: base_link
    min_x: -1.0
    max_x: 0.1
    min_y: -0.5
    max_y: 0.5
    min_z: -0.1
    max_z: 0.1
- name: speckle_filter
  type: laser_filters/LaserScanSpeckleFilter
  params:
    filter_type: 0
    max_range: 2.0
    max_range_difference: 0.1
    filter_window: 2